#!/bin/bash

# Get NYC traffic data
curl -O http://207.251.86.229/nyc-links-cams/LinkSpeedQuery.txt

CSVFILENAME=$(ls | grep *.txt)

# Convert tabs to spaces
vim ${CSVFILENAME} -s vimscript

# Convert csv to JSON
python3 convert_csv_to_json.py ${CSVFILENAME}

# Move JSON file to datasource directoy
mv *.json ../datasource/.

# Clean up
rm ${CSVFILENAME}
